.TH qtqr 1 "April 27 2011" "qtqr"

.SH NAME
qtqr \- QtQR

.SH SYNOPSIS
.B qtqr
.br

.SH DESCRIPTION
QtQR is a Qt based software that let's you generate QR Codes easily,
scan an image file for QR Codes and decode them or use your webcam to
scan a printed one.

 This command will launch QtQR.

.SH BUGS
If you find any bugs, please report them at http://bugs.launchpad.net/qr-tools.

.SH DEVELOPMENT
The development of qtqr is managed at http://launchpad.net/qr-tools, where you can find the source code and report bugs.

.SH AUTHOR
This man page was originally written by David Green <david4dev@gmail.com>.

